import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { EnvFile } from "../configure/env-file.ts";
import { findRepoRoot, resolveActiveDeployment } from "../configure/paths.ts";

/**
 * Reads the active deployment file (installs/<base-domain>.local) and
 * produces a Helm values override at
 *   deploy/helm/x1agent/values.<baseDomain>.yaml
 *
 * The deployment file is owned by `mise run configure` (deployment
 * mode). The base chart's defaults supply structure; this override
 * fills in cloud bindings, image refs, non-secret config, and the GSM
 * secret names. Secrets themselves never appear in the values file —
 * they stay in GSM and ESO syncs them at runtime.
 */

export interface RenderInput {
  envPath: string;
  chartDir: string;
  imageTag: string;
}

export interface RenderResult {
  valuesPath: string;
  release: string;
  baseDomain: string;
}

export function defaultPaths(): {
  envPath: string;
  chartDir: string;
  terraformDir: string;
} {
  const root = findRepoRoot();
  // envPath resolves to the ACTIVE deployment file. Throws helpfully
  // when no deployment exists yet — caller surfaces the error.
  const { path } = resolveActiveDeployment();
  return {
    envPath: path,
    chartDir: resolve(root, "deploy/helm/x1agent"),
    terraformDir: resolve(root, "deploy/terraform/gcp"),
  };
}

/**
 * Write a `terraform.tfvars` from .env.local at the GCP terraform module
 * dir. The terraform module reads project_id / base_domain (required)
 * and several optional knobs. This keeps the generation in one place
 * so `mise run install:plan` and `terraform plan` see identical inputs.
 */
export interface TerraformVarsResult {
  tfvarsPath: string;
}
export function renderTerraformVars(input: {
  envPath: string;
  terraformDir: string;
}): TerraformVarsResult {
  const env = new EnvFile(input.envPath);
  const provider = env.get("CLOUD_PROVIDER");
  if (provider !== "gcp") {
    throw new Error(
      `CLOUD_PROVIDER=${provider ?? "(unset)"} — terraform module only supports 'gcp' in v1.`,
    );
  }
  const projectId = required(env, "GCP_PROJECT_ID");
  const baseDomain = required(env, "BASE_DOMAIN");
  const region = env.get("GCP_REGION") || "us-central1";

  const lines = [
    `# Generated by \`mise run install:plan\`. DO NOT hand-edit.`,
    `# Source: ${input.envPath}`,
    ``,
    `project_id  = ${q(projectId)}`,
    `base_domain = ${q(baseDomain)}`,
    `region      = ${q(region)}`,
    ``,
  ];
  // Pass-through optional toggles when set in .env.local.
  const passThroughBool = (envName: string, tfName: string) => {
    const v = env.get(envName);
    if (v === undefined) return;
    lines.push(`${tfName} = ${v.toLowerCase() === "true" ? "true" : "false"}`);
  };
  const passThroughString = (envName: string, tfName: string) => {
    const v = env.get(envName);
    if (!v) return;
    lines.push(`${tfName} = ${q(v)}`);
  };
  passThroughBool("GCP_ENABLE_AUTOSCALING", "enable_autoscaling");
  passThroughBool("GCP_USE_SPOT_FOR_SESSIONS", "use_spot_for_sessions");
  passThroughBool("GCP_CREATE_DNS_ZONE", "create_dns_zone");
  passThroughString("GCP_NODE_MACHINE_TYPE", "node_machine_type");

  const tfvarsPath = resolve(input.terraformDir, "terraform.tfvars");
  writeFileSync(tfvarsPath, lines.join("\n") + "\n", { mode: 0o600 });
  return { tfvarsPath };
}

export function render(input: RenderInput): RenderResult {
  const env = new EnvFile(input.envPath);

  const provider = env.get("CLOUD_PROVIDER");
  if (provider !== "gcp") {
    throw new Error(
      `CLOUD_PROVIDER=${provider ?? "(unset)"} — installer only supports 'gcp' in v1.\n` +
        `Run \`mise run configure\` and pick GCP.`,
    );
  }

  const baseDomain = required(env, "BASE_DOMAIN");
  const projectId = required(env, "GCP_PROJECT_ID");
  const adminEmails = required(env, "PLATFORM_ADMIN_EMAILS");
  // ACME account email for Let's Encrypt — defaults to the first
  // admin. Operator can override by setting TLS_EMAIL in installs/<>.local.
  const tlsEmail =
    env.get("TLS_EMAIL") || adminEmails.split(",")[0]?.trim() || adminEmails;

  // Image references are derived from the AR repo + a single tag the
  // installer captured. Single-tag-for-all-images keeps this simple
  // until per-component versioning becomes useful.
  const region = env.get("GCP_REGION") || "us-central1";
  const arRepo = env.get("ARTIFACT_REGISTRY") ||
    `${region}-docker.pkg.dev/${projectId}/x1agent`;
  const tag = input.imageTag;

  const yaml =
    `# Generated by \`mise run install:plan\`. DO NOT hand-edit.\n` +
    `# Re-run that task after changing .env.local.\n` +
    `# Source: ${input.envPath}\n` +
    `\n` +
    `baseDomain: ${q(baseDomain)}\n` +
    `\n` +
    `cloud:\n` +
    `  provider: gcp\n` +
    `  gcp:\n` +
    `    projectId: ${q(projectId)}\n` +
    `    region: ${q(region)}\n` +
    // workloadIdentityServiceAccount is a terraform output; the
    // installer wires it in after `terraform apply`.
    `    workloadIdentityServiceAccount: "x1agent-api@${projectId}.iam.gserviceaccount.com"\n` +
    `    sessionWorkloadIdentityServiceAccount: "x1agent-session@${projectId}.iam.gserviceaccount.com"\n` +
    `    artifactRegistry: ${q(arRepo)}\n` +
    `\n` +
    `tls:\n` +
    `  clusterIssuer: x1agent-letsencrypt\n` +
    `  email: ${q(tlsEmail)}\n` +
    `\n` +
    // Anthropic credential source — drives api Deployment env, the
    // session ServiceAccount's WI annotation, and the GSM ANTHROPIC_API_KEY
    // ExternalSecret gate. Defaults to vertex when CLOUD_PROVIDER=gcp;
    // operator can flip via .env.local ANTHROPIC_PROVIDER=api_key.
    renderAnthropicSection(env, projectId) +
    `\n` +
    `images:\n` +
    `  api:\n` +
    `    repository: ${q(arRepo + "/api")}\n` +
    `    tag: ${q(tag)}\n` +
    `  app:\n` +
    `    repository: ${q(arRepo + "/app")}\n` +
    `    tag: ${q(tag)}\n` +
    `  preview:\n` +
    `    repository: ${q(arRepo + "/preview")}\n` +
    `    tag: ${q(tag)}\n` +
    // agent + sidecar — session pods reference these via the api's
    // AGENT_IMAGE / SIDECAR_IMAGE env (see helm chart api template).
    // Without them set, session create succeeds at the K8s API but
    // kubelet ImagePull fails.
    `  agent:\n` +
    `    repository: ${q(arRepo + "/agent")}\n` +
    `    tag: ${q(tag)}\n` +
    `  sidecar:\n` +
    `    repository: ${q(arRepo + "/sidecar")}\n` +
    `    tag: ${q(tag)}\n` +
    `  mcpOAuthProxy:\n` +
    `    repository: ${q(arRepo + "/mcp-oauth-proxy")}\n` +
    `    tag: ${q(tag)}\n` +
    `\n` +
    `config:\n` +
    `  PLATFORM_NAME: ${q("x1agent")}\n` +
    `  PLATFORM_ADMIN_EMAILS: ${q(adminEmails)}\n` +
    `  ALLOWED_DOMAINS: ${q(env.get("ALLOWED_DOMAINS") || "")}\n` +
    `  GOOGLE_OAUTH_SCOPES: ${q(env.get("GOOGLE_OAUTH_SCOPES") || "")}\n` +
    `  ANTHROPIC_MODEL: ${q(env.get("ANTHROPIC_MODEL") || "")}\n` +
    `\n` +
    // Capability gating — wired from the configure wizard's
    // "Graph + vector provider?" prompt. "none" means hide.
    `providers:\n` +
    `  graph: ${q(env.get("PROVIDER_GRAPH") || "none")}\n` +
    `  vector: ${q(env.get("PROVIDER_VECTOR") || "none")}\n` +
    // Per-kind image repos — pinned to the same Artifact Registry as
    // api/app. The graph-surrealdb image is built + pushed by the
    // install orchestrator's build phase; tag tracks api.
    `  graphSurrealdb:\n` +
    `    image:\n` +
    `      repository: ${q(arRepo + "/graph-surrealdb")}\n` +
    `      tag: ${q(tag)}\n` +
    // Override the chart's literal default with the install-config value.
    // Generated + rotated via deploy/scripts/rotate-surrealdb-password.sh.
    // When unset we omit the key so the chart's `| default ...` runs —
    // keeps fresh installs working before the rotation script is run.
    (env.get("SURREALDB_ROOT_PASSWORD")
      ? `    rootPassword: ${q(env.get("SURREALDB_ROOT_PASSWORD")!)}\n`
      : "");

  const valuesPath = resolve(
    input.chartDir,
    `values.${baseDomain}.yaml`,
  );
  writeFileSync(valuesPath, yaml, { mode: 0o600 });

  return {
    valuesPath,
    release: `x1agent`,
    baseDomain,
  };
}

function renderAnthropicSection(env: EnvFile, gcpProjectId: string): string {
  const provider = env.get("ANTHROPIC_PROVIDER") || "vertex";
  if (provider === "vertex") {
    const region = env.get("CLOUD_ML_REGION") || "us-east5";
    const vertexProj = env.get("ANTHROPIC_VERTEX_PROJECT_ID") || gcpProjectId;
    return (
      `anthropic:\n` +
      `  provider: vertex\n` +
      `  vertexRegion: ${q(region)}\n` +
      `  vertexProjectId: ${q(vertexProj)}\n`
    );
  }
  // api_key path — region/project not needed; the ANTHROPIC_API_KEY
  // ExternalSecret binding (left in values.yaml defaults) supplies the
  // env at runtime via GSM.
  return `anthropic:\n  provider: api_key\n`;
}

function required(env: EnvFile, key: string): string {
  const v = env.get(key);
  if (!v) {
    throw new Error(
      `${key} not set in .env.local. Run \`mise run configure\` first.`,
    );
  }
  return v;
}

function q(s: string): string {
  // Quote everything for safety; YAML doesn't mind.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
