export type RemoteMcpAttachment = { name: string; url: string };

export type StdioMcpDefinition = {
  name: string;
  command: string;
  args: string[];
  env: Record<string, string>;
};

export const PLATFORM_MCP_FILES = [
  ["x1agent", "x1-mcp.ts"],
  ["files", "files-mcp.ts"],
  ["sheets", "sheets-mcp.ts"],
  ["docs", "docs-mcp.ts"],
  ["calendar", "calendar-mcp.ts"],
  ["email", "email-mcp.ts"],
] as const;

export function buildPlatformMcpDefinitions(options: {
  tsxPath: string;
  sourceDir: string;
  sidecarUrl: string;
  resolvePath: (dir: string, file: string) => string;
}): StdioMcpDefinition[] {
  return PLATFORM_MCP_FILES.map(([name, file]) => ({
    name,
    command: options.tsxPath,
    args: [options.resolvePath(options.sourceDir, file)],
    env: { SIDECAR_URL: options.sidecarUrl },
  }));
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlKey(value: string): string {
  return JSON.stringify(value);
}

export function parseRemoteMcpAttachments(
  raw: string | undefined,
  warn: (message: string) => void = console.warn,
): RemoteMcpAttachment[] {
  if (!raw) return [];
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) throw new Error("expected an array");
    return parsed.filter(
      (entry): entry is RemoteMcpAttachment =>
        typeof entry === "object" &&
        entry !== null &&
        typeof (entry as RemoteMcpAttachment).name === "string" &&
        (entry as RemoteMcpAttachment).name.length > 0 &&
        typeof (entry as RemoteMcpAttachment).url === "string" &&
        /^http:\/\/127\.0\.0\.1:\d+(?:\/.*)?$/.test(
          (entry as RemoteMcpAttachment).url,
        ),
    );
  } catch (error) {
    warn(
      `MCP_REMOTE_ATTACHMENTS_JSON parse failed: ${(error as Error).message}`,
    );
    return [];
  }
}

export function renderCodexMcpConfig(
  stdioServers: StdioMcpDefinition[],
  remoteServers: RemoteMcpAttachment[],
): string {
  const sections: string[] = [
    "# Auto-generated by the x1agent Codex runtime.",
    "# This file belongs to the session-private CODEX_HOME.",
  ];
  const configuredNames = new Set<string>();

  for (const server of stdioServers) {
    if (configuredNames.has(server.name)) continue;
    configuredNames.add(server.name);
    const env = Object.entries(server.env)
      .map(([key, value]) => `${tomlKey(key)} = ${tomlString(value)}`)
      .join(", ");
    sections.push(
      `[mcp_servers.${tomlKey(server.name)}]`,
      `command = ${tomlString(server.command)}`,
      `args = [${server.args.map(tomlString).join(", ")}]`,
      `env = { ${env} }`,
    );
  }

  for (const server of remoteServers) {
    // Platform MCP names are reserved. A catalog attachment must never
    // shadow x1agent (or make config.toml invalid with a duplicate table).
    if (configuredNames.has(server.name)) continue;
    configuredNames.add(server.name);
    sections.push(
      `[mcp_servers.${tomlKey(server.name)}]`,
      `url = ${tomlString(server.url)}`,
    );
  }

  return `${sections.join("\n")}\n`;
}
